// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWNdPc8IttwH24QX0IXCVgVH-b7pVqSaU',
    appId: '1:415157267112:web:b4643788ab0ae6b8fa709d',
    messagingSenderId: '415157267112',
    projectId: 'finance-88dcd',
    authDomain: 'finance-88dcd.firebaseapp.com',
    storageBucket: 'finance-88dcd.firebasestorage.app',
    measurementId: 'G-6JB1Z1HDS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsmqUC5TTcZexIre7R8YwMrZGDBNoIrQ',
    appId: '1:415157267112:android:139ab457bb468e53fa709d',
    messagingSenderId: '415157267112',
    projectId: 'finance-88dcd',
    storageBucket: 'finance-88dcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZ1-6YUerKVf8XOLvPxosh7K6bTXLjvg',
    appId: '1:415157267112:ios:d533283eebddbedbfa709d',
    messagingSenderId: '415157267112',
    projectId: 'finance-88dcd',
    storageBucket: 'finance-88dcd.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpZ1-6YUerKVf8XOLvPxosh7K6bTXLjvg',
    appId: '1:415157267112:ios:d533283eebddbedbfa709d',
    messagingSenderId: '415157267112',
    projectId: 'finance-88dcd',
    storageBucket: 'finance-88dcd.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWNdPc8IttwH24QX0IXCVgVH-b7pVqSaU',
    appId: '1:415157267112:web:dac8452bc7aaeca6fa709d',
    messagingSenderId: '415157267112',
    projectId: 'finance-88dcd',
    authDomain: 'finance-88dcd.firebaseapp.com',
    storageBucket: 'finance-88dcd.firebasestorage.app',
    measurementId: 'G-TW9ESRPZ0P',
  );
}
